"""
Django settings for app2 project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^x2sqtzyopq8c!+ts)9r47t*9fo5ctcul#xh7f2yd4wk_$mu*7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'django.contrib.sites',
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',

    
    'main',
    'cart',
    'users',
    'orders',
    'payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    "allauth.account.middleware.AccountMiddleware",
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        "SCOPE": [
            "profile",
            "email",
        ],
        'APP': {
            'client_id': '649782090779-aioq4b7kn7bn6g7vrr9g0bq6c68cf468.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    },
    'github': {
        'SCOPE': [
            'user',
            'repo',
            'read:org',
        ],
        'APP': {
            'client_id': 'Ov23lizrHeZkJWMX5Q4I',
            'secret': 'e01736c996c1a5461e6e1c882a078f116109e3fb',
            'key':''
            
        }
    }
}


ROOT_URLCONF = 'app2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'app2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'pizza',
        'USER':'pizza',
        'PASSWORD':'pizza',
        'HOST':'localhost',
        'PORT':'5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL='media/'
MEDIA_ROOT=BASE_DIR/'media'

CART_SESSION_ID='cart'

AUTH_USER_MODEL='users.User'
STRIPE_PUBLISHABLE_KEY='pk_test_51QrfneGGYzjuAv3nQcZdTlcRn3WbOefPPGUnE9gxMvXeeNaJtgyLjHgRtZLIbSAmEHKelcELiZOzlfw17S5qoGZT0093RC1xsj'
STRIPE_SECRET_KEY='sk_test_51QrfneGGYzjuAv3nRzt2WsHTDlSGxiHCZRxNa3c5XGouqLvf2DldaVHRSH65bO4Dccqxh5s3YUEbi5rb6ISeL4Sq00KZwBuWLU'
STRIPE_API_VERSION='2022-08-01'
STRIPE_WEBHOOK_SECRET='whsec_e8349d4811e1ca1b3fa6831c413c5f117e956d2593b557f8a79ae62f63340cfd'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID=1
# редирект после логина или выхода
LOGIN_REDIRECT_URL='/shop/'
LOGOUT_REDIRECT_URL='/'

SOCIALACCOUNT_LOGIN_ON_GET=True

#обязательный запрос почты
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
UNFOLD = {
    "STUDIO": True,  # Включает Studio
}