# Generated by Django 5.1.4 on 2025-03-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
